alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: practice-godot-game-project-expo
    match:
      path:
        prefix: /
name: dolphin-app
region: sfo
static_sites:
- environment_slug: html
  github:
    branch: main
    repo: ccrawford4/practice-godot-game
  name: practice-godot-game-project-expo
  source_dir: project/exports/web